######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 5 10:35:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . dog
INCLUDEPATH += . dog

# Input
HEADERS += animalinterface.h mainprocess.h dog/dog.h
SOURCES += main.cpp mainprocess.cpp dog/dog.cpp
