######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 5 10:20:24 2013
######################################################################

TEMPLATE = lib
TARGET = dog
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += plugin
# Input
HEADERS += dog.h ../animalinterface.h
SOURCES += dog.cpp
