######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 5 10:45:17 2013
######################################################################

TEMPLATE = lib
TARGET = bird
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += plugin
# Input
HEADERS += bird.h ../animalinterface.h
SOURCES += bird.cpp
