######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 5 10:03:55 2013
######################################################################

TEMPLATE = lib
TARGET = fish
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += plugin

# Input
HEADERS += fish.h ../animalinterface.h
SOURCES += fish.cpp
